server:
  port: 8082

spring:
  application:
    name: user-service
  h2:
    console.enabled: true
    console:
      path: /h2-console
      enabled: true
      settings:
        trace: false
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:user_db_store;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driverClassName: org.h2.Driver
    initialize: true
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    baselineOnMigrate: true
    validateOnMigrate: false
    enabled: true
    locations: classpath:db/migration/h2
    url: jdbc:h2:mem:user_db_store;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    user: sa
    password: password
    depends-on: entityManagerFactory
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: none #none, create, create-drop, update
      show-sql: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        id:
          new_generator_mappings: false
        jdbc:
          time_zone: UTC+1
        show_sql: false
    show-sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER


app:
  jwt:
    authorities:
      key: roles
    expirationDateInMs: 86400000
    header:
      string: Authorization
    jwtCookieName: user-service
    jwtRefreshCookieName: user-service-refresh
    refreshExpiration: 8640
    refreshExpirationDateInMs: 8640
    signing:
      key: "YFJFqggP14cyMKLZiGtDJUCnvggxQd7VahdoqUnkFNTxbFBEMxhsiwzoVacMO98z8PlFVb4sIFOqIGoF3uNIrvG98g7/piE/bOQxM8zaFYc8Dlqamwp0bGpjKepU16xNtd2vlUZ1Aki7F459ODvhK7rD6kCMOzRB+d6TwNIsNJrTpVBAQlR7cicLU5cJluJi+gavVhmoDw6W1lfUHkbUEBtqP6C+T/Ksn9NPQOTaujE9TOnNVgtgDHszw8GpoFk0WWwN1HewIq4ZcbE0i4053I8eEDLF50e9O5juySulUGBYHFK0HeQbDNZP8riIIWsEYt8o2NRf4TUMIrfZo3I0xA=="
    token:
      prefix: Bearer
      validity: 86400
      validity-remember-me: 2592000